dh_doctrine_audit:
    # Configuration reference available at:
    # https://github.com/DamienHarper/DoctrineAuditBundle#configuration

    entities:
        App\Entity\KnowFrom: ~   # all MyAuditedEntity1 properties are audited
        App\Entity\Application: ~   # all MyAuditedEntity1 properties are audited
        App\Entity\ApplicationComments: ~   # all MyAuditedEntity1 properties are audited
        App\Entity\Attender: ~   # all MyAuditedEntity1 properties are audited
        App\Entity\AttenderCompany: ~   # all MyAuditedEntity1 properties are audited
        App\Entity\EmailAddress: ~   # all MyAuditedEntity1 properties are audited
        App\Entity\PhoneNumber: ~   # all MyAuditedEntity1 properties are audited
        App\Entity\FieldOfWork: ~   # all MyAuditedEntity1 properties are audited
        App\Entity\Happening: ~   # all MyAuditedEntity1 properties are audited
        App\Entity\ProfileLinks: ~   # all MyAuditedEntity1 properties are audited
        App\Entity\User: ~   # all MyAuditedEntity1 properties are audited
#        MyBundle\Entity\MyAuditedEntity2:
#            ignored_columns:                  # MyAuditedEntity2 properties to be ignored by the audit process
#                - createdAt
#                - updatedAt
    table_prefix: '__'
    table_suffix: '_audit'

#viewwer
#    resource: "@DHDoctrineAuditBundle/Controller/"
#    type: annotation


